# Multiple Linear Regression

## Importing the libraries

In [110]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [111]:
tf.__version__

'2.15.0'

## Importing the dataset

In [112]:
df = pd.read_csv('50_Startups.csv')
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(X)
print(y)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

##  Encoding Categorical Data

In [113]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

#Splitting the dataset into the Training set and Test set

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0 )

# Feature Scaling

In [115]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Artificial Neural Network model on the Training set

In [116]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer

In [117]:
ann.add(tf.keras.layers.Dense(units  = 6, activation = 'relu'))

# Adding the second hidden layer

In [118]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Adding the output layer

In [119]:
ann.add(tf.keras.layers.Dense(units = 1))

# Compiling the ANN

In [120]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Training the ANN

In [124]:
ann.fit(X_train, y_train, batch_size = 1, epochs = 10000)

Streaming output truncated to the last 5000 lines.
40/40 [==============================] - 0s 3ms/step - loss: 62317288.0000
Epoch 7502/10000
40/40 [==============================] - 0s 3ms/step - loss: 62538152.0000
Epoch 7503/10000
40/40 [==============================] - 0s 2ms/step - loss: 62526024.0000
Epoch 7504/10000
40/40 [==============================] - 0s 3ms/step - loss: 62351672.0000
Epoch 7505/10000
40/40 [==============================] - 0s 3ms/step - loss: 62267968.0000
Epoch 7506/10000
40/40 [==============================] - 0s 3ms/step - loss: 62287564.0000
Epoch 7507/10000
40/40 [==============================] - 0s 3ms/step - loss: 62283912.0000
Epoch 7508/10000
40/40 [==============================] - 0s 3ms/step - loss: 62350344.0000
Epoch 7509/10000
40/40 [==============================] - 0s 3ms/step - loss: 62337708.0000
Epoch 7510/10000
40/40 [==============================] - 0s 3ms/step - loss: 62278228.0000
Epoch 7511/10000
40/40 [======================

## Predicting the Test set results

In [125]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1/1 [==============================] - 0s 23ms/step
[[104308.31 103282.38]
 [136951.56 144259.4 ]
 [131981.5  146121.95]
 [ 77466.88  77798.83]
 [169249.84 191050.39]
 [111115.97 105008.31]
 [ 62435.64  81229.06]
 [105243.29  97483.56]
 [113046.2  110352.25]
 [161365.45 166187.94]]


**Evaluating the model performance**

In [126]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9053081011452598